#This is just a template settings.yaml file
'homeassistant_api_key': '' #Long lived access key
'homeassistant_url': '' #Self explanatory
'ai': 'gemini-pro' #gemini-pro is the only valid answer right now
'ai_api_key': 'AIzaSyDNxm33CC7goi_6Mkf-bnIsZG9PzPV-ZNY' #Google AI API Key
'name': 'isaac' #What do you want to call Isaac? Maybe Rick, Jammy, Example 3, or Example 4.
'ai_images_output_directory': '/home/James/Pictures/AI' #Where should the ai generated images be outputted?
'hugging_face_access_token': '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' #Hugging face access token
'hugging_face_text2image_model': 'https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0' #API Inference path to the image gneration model you want to use