'speech_recogniser': 'google'
'vosk_model_name': 'main/vosk-small'
'homeassistant_api_key': 'That was dangerous. Why did .gitignore not ignore this??'
'homeassistant_url': 'This TOO?!'
'google_bard_cookie_key': 'Oh Man! Cant believe I let it out.'
